// postercreator/src/views/editor/module/materialList.vue
<template>
  <div align="left">
    <el-divider content-position="left">表格</el-divider>
    <div class="item">
      <chart type="pie"></chart>
      <chart type="bar"></chart>
    </div>
    <el-divider content-position="left">图形</el-divider>
    <div class="item">
      <shape type="polygon"></shape>
      <shape type="star"></shape>
      <shape type="sector"></shape>
      <shape type="flower"></shape>
      <shape type="circle"></shape>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import chart from "./chart.vue";
import shape from "./shape.vue";
export default defineComponent({
  components: {
    chart,
    shape,
  },
  setup() {
    return {};
  },
});
</script>

<style scoped>
.item {
  display: inline-block;
}
</style>

// h5creator/src/page/editor/module/materialList.tsx
import material from   './materialList.module.scss'
import { Divider } from 'antd';
import Chart from './chart'
import Shape from './Shape'
function MaterialList(){
    return(
        <div>
            <Divider>表格</Divider>
            <div className={material.item}>
                <Chart type='pie'></Chart>
                <Chart type='bar'></Chart>
            </div>
            <Divider>图形</Divider>
            <div className={material.item}>
            <Shape type='polygon'></Shape>
            <Shape type='star'></Shape>
            <Shape type='sector'></Shape>
            <Shape type='flower'></Shape>
            <Shape type='circle'></Shape>
            </div>
        </div>
    )
}

export default MaterialList
