// h5creator/src/page/editor/module/backgroundList.tsx
import { useDispatch } from 'react-redux';
import ModuleUtil from '../../../lib/ModuleUtil';
import { SketchPicker } from 'react-color'
import './backgroundList.scss'
import editInfo from '../../../redux/edit';
import { Popover } from 'antd';
import { useEffect, useState } from 'react';
import { getImageList } from '../../../api/api';
function BackgroundList() {
  const dispatch = useDispatch()
  const colorList = ['red', 'green', 'blue', 'black', 'white', 'gray', 'yellow', 'gold', 'greenyellow', 'brown', 'aqua']
  const [imageList, setImageList] = useState([])
  useEffect(() => {
    searchImageList()
    return () => { }
  }, [])
  const searchImageList = async () => {
    let res = await getImageList({ type: 'back' })
    let imageList = res.map((item: any) => { return item.image_url })
    setImageList(imageList)
  }
  const selectColor = (color: string) => {
    dispatch({ type: 'selectBackColor', color: color })
  };
  const selectBack = async (url: string) => {
    let imageInfo = await ModuleUtil.getBackImageInfo(url);
    dispatch({ type: "addBackImage", image: imageInfo });
  };
  const handleColorChange = (value: any) => {
    let rgba = `rgba(${value.rgb.r},${value.rgb.g},${value.rgb.b},${value.rgb.a})`
    selectColor(rgba)

  }
  let backgroundColor = editInfo.postInfo.background.color
  let imageDom = imageList.map((item, index) => {
    return <div className='image-item' key={index} onClick={() => { selectBack(item) }}>
      <img src={item} alt='加载失败' />
    </div>
  })
  let colorDom = colorList.map((item, index) => {
    return <div className='color-item' onClick={() => { selectColor(item) }} key={index} style={{ 'backgroundColor': item }} ></div>
  })
  let selectedColorDom = <div className='color-item'  >
    <div className='selected-item' style={{ 'backgroundColor': backgroundColor }}>

    </div>
  </div>
  return (
    <>
      <div className='color-List'>
        {colorDom}
        <Popover placement="rightTop" content={<SketchPicker color={backgroundColor} onChange={handleColorChange}></SketchPicker>} trigger="click">
          {selectedColorDom}
        </Popover>


      </div>
      {imageDom}
    </>
  )
}

export default BackgroundList

// postercreator/src/views/editor/module/backgroundList.vue
<template>
  <div class="color-List">
    <div
      class="color-item"
      v-for="(item, index) in colorList"
      :key="index"
      :style="{ backgroundColor: item }"
      @click="selectColor(item)"
    ></div>
    <div>
      <div class="color-item">
        <div class="block-color">
          <color-picker
            v-model="backModel.color"
            show-alpha
            :style="{
              backgroundColor: backModel.color,
            }"
          ></color-picker>
        </div>
      </div>
    </div>
  </div>

  <div v-infinite-scroll="search">
    <div
      class="image-item"
      v-for="(url, index) in imageList"
      @click="selectBack(url)"
      :key="index"
    >
      <el-image style="width: 80px; height: 80px" :src="url" fit="contain">
      </el-image>
    </div>
  </div>
</template>

<script lang="ts">
import {
  computed,
  defineComponent,
  onMounted,
  reactive,
  ref,
  watch,
} from "vue";
import { useStore } from "vuex";
import ModuleUtil from "@/lib/ModuleUtil";
import { getImageList } from "@/api/api";
import ColorPicker from "@/components/color-picker/index";
export default defineComponent({
  components: {
    ColorPicker,
  },
  setup() {
    const store = useStore();
    const colorList = ref([
      "red",
      "green",
      "blue",
      "black",
      "white",
      "gray",
      "yellow",
      "gold",
      "greenyellow",
      "brown",
      "aqua",
    ]);
    onMounted(async () => {
      search();
    });
    let pageNo = 1;
    let pageSize = 30;
    const search = async () => {
      let res = await getImageList({
        type: "back",
        pageNo: pageNo++,
        pageSize,
      });
      let list = res.map((item) => item.image_url);
      imageList.value = [...imageList.value, ...list];
    };
    const imageList = ref(<any>[]);
    const selectBack = async (url: string) => {
      store.commit("setEditModuleToBack");
      let imageInfo = await ModuleUtil.getBackImageInfo(url);
      store.commit("addBackImage", imageInfo);
      backModel.value.color = undefined;
      store.commit("pushBack");
    };
    const selectColor = async (color: string) => {
      store.commit("setEditModuleToBack");
      backModel.value.image = undefined;
      backModel.value.color = color;
      store.commit("pushBack");
    };
    const backModel = computed(() => {
      return store.state.postInfo.background;
    });

    // store.commit('setEditModuleToBack')
    return { imageList, selectBack, colorList, backModel, selectColor, search };
  },
});
</script>

<style lang="scss" scoped>
.image-item {
  width: 80px;
  height: 80px;
  margin: 5px;
  float: left;
  border: 1px solid rgb(230, 230, 230);
  cursor: pointer;
  &:hover {
    transform: scale(1.1);
    transition: 0.1s;
  }
}
.color-List {
  width: 100%;
  display: inline-block;
}
.color-item {
  width: 30px;
  height: 30px;
  float: left;
  margin: 5px;
  border: 1px solid gray;
  border-radius: 5px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}
.block-color {
  height: 25px;
  width: 25px;
  border-radius: 5px;
  overflow: hidden;
  box-shadow: 0 0 4px rgb(175, 175, 175);
}
</style>
