// h5creator/src/page/editor/module/codeItem.tsx
/* eslint-disable react-hooks/exhaustive-deps */
import codeItemScss from './codeItem.module.scss'
import * as QRCode from 'qrcode';
import { useEffect, useRef } from 'react';
import ModuleUtil from '../../../lib/ModuleUtil';
import { useDispatch } from 'react-redux';
interface option {
  width: number,
  color: {
    dark: string,
    light: string,
  },
  backImage?: string
}
function CodeItem(props: { option: option }) {
  const codeRef = useRef<HTMLDivElement>(null)
  const dispatch = useDispatch()
  useEffect(() => {
    QRCode.toCanvas('二维码编辑', props.option, (err: any, canvas: any) => {
      (codeRef.current as HTMLDivElement).append(canvas)
      if (err) throw err;
    });
    return () => {

    };
  }, []);
  const addCode = async () => {
    let codeInfo = await ModuleUtil.getAddCodeInfo({
      text: "二维码编辑",
      colorDark: props.option.color.dark,
      colorLight: props.option.color.light,
      backImage: props.option.backImage,
    });
    dispatch({ type: "addCode", 'code': codeInfo })
  };
  let backImage
  if (props.option.backImage) {
    backImage = <img className={codeItemScss.backImage} src={props.option.backImage} alt='加载失败' />
  }
  return (

    <div className={codeItemScss.code} ref={codeRef} onClick={addCode}>
      {backImage}
    </div>
  )
}

export default CodeItem

// postercreator/src/views/editor/module/codeItem.vue
<template>
  <div ref="code" class="code" @click="addCode">
    <img v-if="options.backImage" class="backImage" :src="options.backImage" />
  </div>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from "vue";
import * as QRCode from "qrcode";
import ModuleUtil from "@/lib/ModuleUtil";
import { useStore } from "vuex";
import { operItem } from "@/interface/module";
import EditPositionUtil from "../lib/editPositionUtil";
export default defineComponent({
  props: {
    options: {
      type: Object,
      default: {},
    },
  },
  setup(props) {
    const store = useStore();
    let code = ref(null as unknown as HTMLElement);
    onMounted(() => {
      QRCode.toCanvas("二维码编辑", props.options, (err: any, canvas: any) => {
        code.value.append(canvas);
        if (err) throw err;
      });
    });
    const addCode = async () => {
      let codeInfo = <operItem>await ModuleUtil.getAddCodeInfo({
        text: "二维码编辑",
        colorDark: props.options.color.dark,
        colorLight: props.options.color.light,
        backImage: props.options.backImage,
        pointType: "normal",
        eyeType: "N-A",
      });
      let position = EditPositionUtil.getShowEditCenterPosition();
      codeInfo.top = position.top - codeInfo.height / 2;
      codeInfo.left = position.left - codeInfo.width / 2;
      store.commit("addCode", codeInfo);
      store.commit("setEditModule", codeInfo.id);
      store.commit("pushBack");
    };
    return { code, addCode };
  },
});
</script>

<style lang="scss" scoped>
.code {
  float: left;
  cursor: pointer;
  position: relative;
}
.backImage {
  position: absolute;
  top: 0;
  left: 0;
  width: 130px;
  height: 130px;
  z-index: -1;
}
</style>
