// postercreator/src/views/editor/operation/background.vue
<template>
  <div
    class="background"
    :style="{
      backgroundColor: background.color,
    }"
  >
    <img
      class="backImage"
      :style="{
        width: `${background.image.width}px`,
        height: `${background.image.height}px`,
        left: `-${background.image.left}px`,
        top: `-${background.image.top}px`,
      }"
      draggable="false"
      v-if="background.image"
      :src="background.image.src"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  props: {
    background: {
      type: Object,
      default: new Object(),
    },
  },
  setup() {
    return {};
  },
});
</script>

<style lang="scss" scoped>
.background {
  width: 100%;
  height: 100%;
  position: absolute;
  left: 0;
  top: 0;
  pointer-events: none;
}
.backImage {
  position: absolute;
}
</style>

// h5creator/src/page/editor/operation/background.tsx
/* eslint-disable jsx-a11y/alt-text */
import { background } from '../../../interface/module'
import './background.module.scss'
interface type {
  background: background
}
function Background(props: type) {
  // let editModule = edit.editModule
  let background = props.background
  let backImage = background.image ? <img
    className="backImage"
    style={{
      width: `${background.image.width}px`,
      height: `${background.image.height}px`,
      left: `-${background.image.left}px`,
      top: `-${background.image.top}px`,
    }}
    draggable="false"
    src={background.image.src}
  /> : <></>
  return (
    <div
      className="background"
      style={{
        backgroundColor: background.color,
      }}

    >
      {
        backImage
      }
    </div>
  )
}
export default Background
