// postercreator/src/views/editor/operation/dText.vue
<template>
  <div
    class="text-content"
    @mousedown="moveEvent"
    :style="{
      width: module.width + 'px',
      height: `${fontScale != 1 ? module.height * fontScale + 'px' : 'auto'}`,
      left: module.left + 'px',
      top: module.top + 'px',
      transform: `rotate(${module.rotate ? module.rotate : 0}deg)`,
      zIndex: module.zindex,
      textAlign: `${module.textAlign}`,
    }"
  >
    <div
      class="Strokecontent"
      v-if="module.strokeWidth != 0"
      :style="{
        ...commonStyle,
        ...{
          textStroke: `${pattern == 'edit' ? 0 : module.strokeWidth}px ${
            module.strokeColor
          }`,
        },
        ...backImageStyle,
      }"
      v-html="module.html"
    ></div>
    <content-input
      v-if="contenteditable === true"
      @blur="contenteditable = false"
      @contentChange="contentChange"
      :style="{
        ...commonStyle,
        ...backImageStyle,
      }"
      :module="module"
    ></content-input>

    <div
      v-show="contenteditable === false"
      class="content"
      @dblclick="dbClickEvent"
      ref="contentShow"
      :style="{
        ...commonStyle,
        ...backImageStyle,
      }"
      v-html="module.html"
    ></div>
    <lock
      :module="module"
      v-if="editModule.id == module.id && pattern == 'edit'"
    ></lock>
    <regulator
      :module="module"
      v-if="editModule.id == module.id && pattern == 'edit'"
      @changeHeight="changeHeight"
    ></regulator>
    <rotate
      :module="module"
      v-if="editModule.id == module.id && pattern == 'edit'"
    ></rotate>
  </div>
</template>

<script lang="ts">
import { useStore } from "vuex";
import {
  computed,
  defineComponent,
  nextTick,
  onMounted,
  ref,
  watch,
} from "vue";
import regulator from "./regulator.vue";
import rotate from "./rotate.vue";
import contentInput from "./contentInput.vue";
import operation from "./common/operation";
import { textShadow } from "@/interface/module";
import Lock from "./lock.vue";
export default defineComponent({
  props: {
    text: {
      type: Object,
      default: new Object(),
    },
    pattern: {
      type: String,
      default: "edit",
    },
  },
  components: {
    regulator,
    rotate,
    Lock,
    contentInput,
  },
  setup(props, ctx) {
    const store = useStore();
    const contenteditable = ref(false);
    onMounted(() => {
      changeHeight();
    });
    const editModule: any = computed(() => {
      return store.state.editModule;
    });
    const module: any = computed(() => {
      return props.text;
    });
    const { moduleMove, resetGroupItem } = operation();
    const selectModel = () => {
      store.commit("setEditModule", module.value.id);
    };

    const contentShow = ref(null as unknown as HTMLElement);
    const changeHeight = () => {
      if (props.pattern != "edit") {
        return;
      }

      if (contentShow.value) {
        module.value.height = contentShow.value.clientHeight;
      }

      if (store.state.group) {
        resetGroupItem(store.state.group);
      }
    };
    const fontSize = computed(() => {
      return module.value.fontSize;
    });
    const lineHeight = computed(() => {
      return module.value.lineHeight;
    });
    const letterSpacing = computed(() => {
      return module.value.letterSpacing;
    });
    const backImageStyle = computed(() => {
      if (module.value.backImage && props.pattern == "show") {
        return {
          backgroundImage: `url('${module.value.backImage}')`,
          backgroundRepeat: `no-repeat`,
          backgroundSize: `cover`,
          WebkitTextFillColor: `transparent`,
          WebkitBackgroundClip: `text`,
        };
      }
      if (module.value.gradient && props.pattern == "show") {
        let gradientList = module.value.gradient;
        let Gradient = "";
        gradientList.forEach((item, index) => {
          Gradient += `${item.color} ${item.offset * 100}%`;
          if (index < gradientList.length - 1) {
            Gradient += ",";
          }
        });
        return {
          backgroundImage: `linear-gradient(${module.value.gradientAngle}deg,${Gradient})`,
          backgroundRepeat: `no-repeat`,
          backgroundSize: `cover`,
          WebkitTextFillColor: `transparent`,
          WebkitBackgroundClip: `text`,
        };
      }
      return {};
    });
    const fontScale = computed(() => {
      let fontSize = module.value.fontSize;
      if (fontSize < 12) {
        return fontSize / 12;
      }
      return 1;
    });
    const textShadow = computed(() => {
      let textShadowList = module.value.textShadowList;

      if (textShadowList.length == 0 || props.pattern == "edit") {
        return "none";
      }
      let result = "";
      textShadowList.forEach((item: textShadow, index: number) => {
        if (index == 0) {
          result =
            result +
            `${item.hShadow}px ${item.vShadow}px ${item.blur}px ${item.color}`;
        } else {
          result =
            result +
            `,${item.hShadow}px ${item.vShadow}px ${item.blur}px ${item.color}`;
        }
      });
      return result;
    });
    const contentChange = (params) => {
      console.log(params);
      module.value.html = params.html;
      module.value.text = params.text;
      module.value.height = params.height;

      if (store.state.group) {
        resetGroupItem(store.state.group);
        store.commit("initGroupSize");
      }
      // changeHeight();
      // if (store.state.group) {

      // }
    };
    const dbClickEvent = () => {
      contenteditable.value = true;
    };
    const moveEvent = () => {
      if (contenteditable.value) {
        return;
      }
      moduleMove(module.value);
    };
    watch([fontSize, lineHeight, letterSpacing], (nv, ov) => {
      nextTick(() => {
        changeHeight();
      });
    });
    const commonStyle = computed(() => {
      return {
        fontSize: `${module.value.fontSize}px`,
        transform: `scale(${fontScale.value})`,
        color: `${
          props.pattern == "show" ? module.value.color : "rgba(0,0,0,0)"
        }`,
        caretColor: module.value.color,
        width: `${module.value.width / fontScale.value}px`,
        fontWeight: `${module.value.bold ? 900 : 400}`,
        textDecoration: `${module.value.textDecoration}`,
        fontStyle: `${module.value.italic ? "italic" : "normal"}`,
        lineHeight: `${module.value.lineHeight}`,
        letterSpacing: `${module.value.letterSpacing}px`,
        opacity: module.value.opacity,
        textShadow: textShadow.value,
        fontFamily: module.value.fontFamily,
      };
    });

    return {
      module,
      moduleMove,
      editModule,
      selectModel,
      changeHeight,
      contentInput,
      fontScale,
      textShadow,
      contentChange,
      contenteditable,
      dbClickEvent,
      moveEvent,
      backImageStyle,
      commonStyle,
      contentShow,
    };
  },
});
</script>

<style lang="scss" scoped>
.text-content {
  position: absolute;
}
.content {
  word-break: break-word;
  white-space: pre-wrap;
  position: relative;
  left: 0;
  transform-origin: 0px 0px;
  &:focus {
    outline: none;
  }
}
.Strokecontent {
  word-break: break-word;
  white-space: pre-wrap;
  position: absolute;
  z-index: -1;
  left: 0;
  transform-origin: 0px 0px;
}
</style>

// h5creator/src/page/editor/operation/dText.tsx

import { CSSProperties, useCallback, useEffect, useRef, useState } from "react"
import { useDispatch, useSelector } from "react-redux"
import { text } from "../../../interface/module"
import './dText.scss'
import Regulator from './regulator'
import Rotate from './rotate'
import edit from "../../../redux/edit"
import eventEmitter from "../../../lib/EventEmitter"

interface type {
  text: text,
  edit?: boolean,
  animate?: any
}
/* eslint-disable react-hooks/exhaustive-deps */
function DText(props: type) {

  let text = props.text
  const [module, setModule] = useState(props.text);
  useEffect(() => {
    setModule({ ...props.text })
  }, [props.text.id])
  useEffect(() => {

    const changeModule = (id: string) => {
      if (id === props.text.id) {
        setModule({ ...props.text })
      }
    }
    eventEmitter.on('changeModule', changeModule)
    return () => {
      eventEmitter.off('changeModule', changeModule)
    }
  }, [props.text]) // eslint-disable-line react-hooks/exhaustive-deps
  let editcom = props.edit ? props.edit : false
  const [textContent] = useState(props.text.text)
  const dispatch = useDispatch()
  const contentInput = useRef<HTMLDivElement>(null)
  let editModule = edit.editModule

  let scale = useSelector((state: any) => state.H5Edit.scale)
  let moveScale = 100 / scale
  let fontScale = 1
  if (module.fontSize < 12) {
    fontScale = module.fontSize / 12
  }

  let style: CSSProperties = {
    width: module.width + 'px'
    , height: `${fontScale !== 1 ? module.height * fontScale + 'px' : 'auto'}`
    , left: module.left + 'px'
    , top: module.top + 'px',
    transform: `rotate(${module.rotate ? module.rotate : 0}deg)`
    , zIndex: module.zindex,
    // TextAlign: module.textAlign
    textAlign: module.textAlign as any
  }
  let strokeContentStyle: CSSProperties = {
    position: 'absolute',
    zIndex: -1,
    fontSize: `${module.fontSize}px`,
    transform: `scale(${fontScale})`,
    color: editcom ? `rgba(0,0,0,0)` : `${module.color}`,
    caretColor: module.color,
    width: `${module.width / fontScale}px`,
    fontWeight: module.bold ? 900 : 400,
    textDecoration: `${module.textDecoration}`,
    fontStyle: `${module.italic ? 'italic' : 'normal'
      } `,
    lineHeight: `${module.lineHeight} `,
    letterSpacing: `${module.letterSpacing}px`,
    opacity: module.opacity,
    fontFamily: module.fontFamily,
    WebkitTextStroke: `${editcom ? 0 : module.strokeWidth}px ${module.strokeColor}`
  }
  let contentStyle: CSSProperties = {
    fontSize: `${module.fontSize}px`,
    transform: `scale(${fontScale})`,
    color: editcom ? `rgba(0,0,0,0)` : `${module.color}`,
    caretColor: module.color,
    width: `${module.width / fontScale}px`,
    fontWeight: module.bold ? 900 : 400,
    textDecoration: `${module.textDecoration}`,
    fontStyle: `${module.italic ? 'italic' : 'normal'
      } `,
    lineHeight: `${module.lineHeight} `,
    letterSpacing: `${module.letterSpacing}px`,
    opacity: module.opacity,
    fontFamily: module.fontFamily,

  }
  const [animate, setAnimate] = useState({} as CSSProperties)
  useEffect(() => {
    let previewAnimate = props.animate
    if (previewAnimate) {
      setAnimate({
        animationName: previewAnimate.keyframe,
        animationDuration: `${previewAnimate.duration / 1000}s`
      })
    } else {
      if (animate) {
        setAnimate({})
      }
    }

  }, [props.animate])// eslint-disable-line react-hooks/exhaustive-deps
  // console.log(1234)
  const changeHeight = () => {
    if (!contentInput.current) {
      return;
    }
    let clientHeight = contentInput.current.clientHeight
    text.height = clientHeight
    setModule({ ...text })
  }
  useEffect(() => {
    setTimeout(() => { changeHeight() })

  }, [module.fontSize, module.lineHeight, module.letterSpacing, module.width])// eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => {
    setModule({ ...props.text })
  }, [props.text])

  const moduleMove = useCallback(() => {
    let module = props.text
    let event = window.event as MouseEvent
    let oriX = event.clientX
    let oriY = event.clientY
    let orileft = module.left
    let oritop = module.top
    dispatch({ type: 'setEditModule', moduleId: module.id })
    window.onmousemove = (event: MouseEvent) => {
      let X = event.clientX
      let Y = event.clientY
      module.left = orileft + (X - oriX) * moveScale
      module.top = oritop + (Y - oriY) * moveScale
      eventEmitter.emit('changeModule', module.id)
    }
    window.onmouseup = () => {
      eventEmitter.emit('updateEditInfo', module.id)
      window.onmousemove = null
      window.onmouseup = null
      module.left = Math.round(module.left)
      module.height = Math.round(module.height)
      module.width = Math.round(module.width)
      module.top = Math.round(module.top)

    }
  }, [props.text, moveScale])


  return (
    <div className='text-content ' style={style} onMouseDown={() => { moduleMove() }} >

      <div style={{ ...animate, ...{ width: `100%`, height: `100%` } }}>
        <div className='content' onInput={(value) => {

          text.text = (value.target as HTMLDivElement).innerText
          changeHeight()
          eventEmitter.emit('changeModule', module.id)
        }}
          onBlur={(value) => {
            text.text = (value.target as HTMLDivElement).innerText
            eventEmitter.emit('changeModule', module.id)
          }}
          suppressContentEditableWarning contentEditable="true" style={strokeContentStyle}>
          {
            (() => {
              if (editcom) {
                return textContent
              } else {
                return module.text
              }
            })()
          }
        </div>
        <div className='content' onInput={(value) => {

          text.text = (value.target as HTMLDivElement).innerText
          changeHeight()
          eventEmitter.emit('changeModule', module.id)
        }}
          onBlur={(value) => {
            text.text = (value.target as HTMLDivElement).innerText
            eventEmitter.emit('changeModule', module.id)
          }}
          suppressContentEditableWarning contentEditable="true" style={contentStyle} ref={contentInput} >
          {
            (() => {
              if (editcom) {
                return textContent
              } else {
                return module.text
              }
            })()
          }
        </div>
        {
          (() => {
            if (editModule.id === module.id && editcom)
              return <> <Regulator minHeight={6} module={module} changeWidth={changeHeight}></Regulator><Rotate module={module}></Rotate></>
          })()
        }

      </div>

    </div>
  )

}
export default DText
